name: CI/CD GitHub Actions
on: [push]
jobs:
  gtest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule init
      - run: git submodule update
      - run: pip install --user cpp-coveralls
      - run: sudo apt-get update -y && sudo apt-get install -y qt5-qmake qt5-default
      - run: ./Tests/tests
 
      - name: Coveralls
        run: coveralls -t ${{ secrets.coveralls_token }} --root . -E ".*external.*" -E ".*tests.*"


  sonarcloud-check:
    needs: gtest-tests
    runs-on: ubuntu-latest
    env:
      SONAR_SCANNER_VERSION: 4.6.1.2450 # Find the latest version in the "Linux" link on this page:
                                        # https://sonarcloud.io/documentation/analysis/scan/sonarscanner/
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
